### ISSUE TITLE
Edit Question: [PATH VARIABLE]

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#18]
**Describe the request**  
Provide de a catalog title 

**Propose what exactly should be changed**  
Translate the catalog titles int German 

**Original setting or content**   
What is the current content or setting e.g. 
<catalog dc:uri="https://rdmorganiser.github.io/terms/questions/ua-ruhr">
<title lang="en">UA Ruhr-Consultation</title>
<title lang="de">UA Ruhr-Consultation</title>

*catalog  text en*  
<catalog dc:uri="https://rdmorganiser.github.io/terms/questions/ua-ruhr">
<title lang="en">Consultation</title>
<title lang="de">Beratung</title>

the same for 

Proposal -> Antragstellung 
archive -> Archivierung 

**Additional context**

**Comment by Bassbiest** [comment]
This is more work than it seems at first, because we need to rewrite the auto catalog creation and the cat_member files to do so.
