### ISSUE TITLE
Links not clickable

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#23]
Question Inhaltliche Einordnung -> Datensätze
De: „§3a BDSG“ (the other link „BDSG“ on this page works)  
En: „German Federal Data Protection Act“

The words are blue and underlined but it is not possible to klick on it (no link)
Tested with chrome and firefox

**Comment by jmfrenzel** [comment]
confirmed: 
"§3a BDSG“ has a blank in the url

**Comment by Bassbiest** [comment]
faulty html

<a ="https:="" www.gesetze-im-internet.de="" bdsg_1990="" __3a.html"="" target="_blank&quot;">§3a BDSG</a>

**Comment by Bassbiest** [comment]
fixed in 6e3d0d59b99a9daf27c249311f7c58b884aa2fa1
