### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#24]
**Describe the bug**
English Version of „Project partners“: Link still not working (see screenshot)
English Version of „Other sensitive data“: DFG Guidelines on the Handling of Reserach Data still not working
German Version of „Datennutzung -> Weitergabe und Veröffentlichung“ „Wenn ja, unter welchen Nutzungsbedingungen oder welcher Lizenz sollen die Daten veröffentlicht bzw. geteilt werden?“ -> Link to „Creative-Commons-Familie“ not working (english version is okay!)
![UARuhr_brokenLinks](https://user-images.githubusercontent.com/51075253/58417257-82cca980-8084-11e9-8abe-8499ba6ed25d.png)

**Comment by Bassbiest** [comment]
@jmfrenzel The following links do not exist anymore 

- http://www.wissgrid.de/publikationen/Leitfaden_Data-Management-WissGrid.pdf 
- http://www.dfg.de/en/research_funding/proposal_review_decision/applicants/submitting_proposal/research_data/index.html

**Comment by jmfrenzel** [comment]
https://www.forschungsdaten.org/index.php/Datei:Leitfaden_Data-Management-WissGrid.pdf  
https://www.dfg.de/en/research_funding/proposal_review_decision/applicants/research_data/index.html
