### ISSUE TITLE
Links open in the same window

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#25]
German and english Version: Rechtliche und ethische Fragen -> Personenbezogene Daten 
German and english Version: Rechtliche und ethische Fragen -> Sensible Daten „In welchem Umfang wird die "informierte Einwilligung" der Betroffenen eingeholt?“

all links open in the same window. As with the other questions, i would suggest to open the links in another tab/window here as well

**Comment by jmfrenzel** [comment]
Can reproduce that. However the option to open a new window/frame is deprecated in html.

To be consistent with the other references in rdmo-catalog  we may 

- [x] add the ` target="_blank"` in the href element
