### ISSUE TITLE
Questions in set Metadata and referencing

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#26]
Catalogue „Consultation“: Metadaten und Referenzierung -> Metadaten „Welche Metadaten werden erhoben? Werden Standards, Ontologien oder Klassifikationen verwendet?“ 

no space for answering the second part of the question

In catalogue „Proposal“: same question or option set but not the same attribute for question „Welche Informationen sind für Außenstehende notwendig, um die Daten zu verstehen (d. h. ihre Erhebung bzw. Entstehung, Analyse sowie die auf ihrer Basis gewonnenen Forschungsergebnisse nachvollziehen) und nachnutzen zu können?“ 

Is this what you wanted?

**Comment by jmfrenzel** [comment]
@smohex 
>no space for answering the second part of the question  

does this refer to the "Andere/Other" text field?

**Comment by jmfrenzel** [comment]
>In catalogue „Proposal“: same question or option set but not the same attribute for question „Welche Informationen sind für Außenstehende notwendig, um die Daten zu verstehen (d. h. ihre Erhebung bzw. Entstehung, Analyse sowie die auf ihrer Basis gewonnenen Forschungsergebnisse nachvollziehen) und nachnutzen zu können?“

>Is this what you wanted?  

No it is not intended u a simple bug. 

Tho goal here was to provide an abstract  `/data-usage/data-sharing-and-re-use/abstract` rather then 

- `consultation/data-usage/data-sharing-and-re-use-interoperability/restriction` twice
- all two  must be removed

**Comment by smohex** [comment]
With "no space for answering the second part" I thought of the question part "Werden Standards, Ontologien oder Klassifikationen verwendet?" Where can this question be answered? 
I wouldn't get the idea to enter an answer to this question in the "Other" text field. But maybe just my opinion!

**Comment by Bassbiest** [comment]
@smohex The question was intended to be answered in the form of a short text, without set options to choose from. We missed changing the widget type. Thank you for noticing.

**Comment by jmfrenzel** [comment]
Specification see  https://confluence.tu-dortmund.de/display/RDMO/Abgleich+Anforderungen+UA+RUHR+mit+rdmo-catalog
