### ISSUE TITLE
Help text "red cross (×)"

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#28]
**Describe the bug**
the color of the cross is black not red. Perhaps you find a way to change it in "black cross" or "little cross" or only "cross".

**To Reproduce**
You find the bug for example here: https://rdmo-demo.rd.ruhr-uni-bochum.de/projects/14/questions/130/
All RDMO-help texts have this bug (english and german).

**Comment by Bassbiest** [comment]
I changed the colour of the cross to an actual red. However, the associated commit will not be visible in this repository. I will close the Issue once the changes are deployed.

**Comment by Bassbiest** [comment]
Changes are deployed, closing issue
