### ISSUE TITLE
Questions "Projektpartner" and "Förderer"

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#29]
Where is the difference between the button „Projektpartner hinzufügen“ („Förderer hinzufügen“) and „Projektpartner“ („Wer fördert das Projekt?“) (within the dataset)? 

If there is a different between it I would suggest to specify the „Projektpartner“/“ Wer fördert das Projekt?“-Question. 
If not, I think the entry in the record would simply be repeated.

**Comment by Bassbiest** [comment]
I would imagine one can cooperate on a project with another institution of another university (project partner) and still, be collectively founded by the DFG (founder)

**Comment by jmfrenzel** [comment]
Funding and Project partners can have multiple sources.
