### ISSUE TITLE
Change question: ua_ruhr/storage-and-long-term-preservation/long-term-preservation-datasets/purpose

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#31]
Speicherung und Langzeitarchivierung -> Langzeitarchivierung: „Aus welchen Gründen müssen die Daten langfristig aufbewahrt werden?“
I would suggest to add „Wenn ja,“ before the question like: "Wenn ja, aus welchen Gründen müssen die Daten langfristig aufbewahrt werden?"
It seems weird if someone answered the question before with „no“

**Comment by Bassbiest** [comment]
Alternatively, we could hide the second questions behind a condition. Only if the first gets answered with yes, the second will be visible.


- [ ] make the question (ua_ruhr/storage-and-long-term-preservation/long-term-preservation-datasets/purpose) conditional on this question (ua_ruhr/storage-and-long-term-preservation/long-term-preservation-datasets/yesno)
