### ISSUE TITLE
Compare catalog rdmo.xml original vs 2018 datamodel 

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#4]
**Is your feature request related to a problem? Please describe.**
Change of data model in rdmo: [v0.1.0 (original)](https://github.com/rdmorganiser/rdmo-catalog/tree/v0.1.0) vs [new 2018](https://github.com/rdmorganiser/rdmo-catalog/tree/74e73503527213d0fcd9ebd48d8ba43fb545421b/rdmorganiser)

**Describe the solution you'd like**
- [x] Verify, that attributes of sections, questions-sets and questions do match.
   - [x] if, not map changes 
- [x] Verify, that question texts and help text and format match 
  - [x] if not, generate an up to date questions/rdmo.xml 
     - [x] create PR at https://github.com/rdmorganiser/rdmo-catalog

**Describe alternatives you've considered**

**Additional context**

**Comment by Bassbiest** [comment]
Pull Request #1 was accepted. Closing Issue.
