### ISSUE TITLE
Compatibility issue H2020 vs. UA Ruhr 

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#40]
**Describe the bug**

For some questions / question sets [H2020 catalog view](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/8b5d7c91bfb24ea1ba1875fc3dd5b5fe12785a19/rdmorganiser/questions/horizon2020.xml) does attribute collections as they are being defined in common catalogs rdmo and ua-ruhr. This creates a incompatibility in the questions (collection fag no set )  when changing the catalog of a project to H2020 whene this project was originally being  filled using  rdmo and ua-ruhr catalogs. 

In rdmo question catalog the question-sets linking to `project/dataset`and  `project/partner` are set up as collections. 

**To Reproduce**
1. install H20202 catalog https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/8b5d7c91bfb24ea1ba1875fc3dd5b5fe12785a19/rdmorganiser/questions/horizon2020.xml project
2. create project in rdmo using rdmo (or  ruaruhr catalog) 
3. add more than one `project/dataset`  or `project/partner`  and fill these text boxes 
4. change the catalog of the projet to H2020 
5. go to answer questions and select a question being linked to one of the following question sets   

question sets   which are not set up as collections: 

`horizon2020/general/topic-description`    
`horizon2020/content-classification/data-existing_data`  
`horizon2020/data-usage/data-storage-and-security-naming_policy`  
`horizon2020/general/topic-description`  
`horizon2020/content-classification/data-existing_data`  
`horizon2020/data-usage/data-storage-and-security-naming_policy`  
`horizon2020/storage-and-long-term-preservation/selection-explanation`  
`horizon2020/storage-and-long-term-preservation/selection-quality`  
`horizon2020/costs/support-additional`  
`horizon2020/general/selection-contact`  

**Expected behavior**
H2020 question sets render as  collections as being defied in rdmo common questions catalog   

**Additional context**

**Comment by smohex** [comment]
In the Horizon catalog, some question sets were originally not marked as a collection. When the catalogs were changed, this resulted in several free fields for a question. This problem has now been solved by setting the problematic question sets as a collection.

**Comment by jmfrenzel** [comment]
In addition to the missing `<is_collection>True</is_collection>` flag the `question-sets` (as being listed above) have empty `<attribute/>` entry.

**Comment by jmfrenzel** [comment]
Issue should be fixed via: 
3e04c691f5321322cbe65d07c532f41423a3c8df  
and Fix of fix   
e86e667f47ebe2ac046d20683a73e00680460060
