### ISSUE TITLE
Add new UA Ruhr project questions 

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#5]
**Is your feature request related to a problem? Please describe.**
The rdmo-catalog-uaruhr project group has decided to add some more questions to satisfy RDM life-cycle and customer needs.  

**Describe the solution you'd like**
- [x]  new  questions/uaruhr-rdmo.xml catalog, which extends [questions/uaruhr-rdmo.xml](https://github.com/rdmorganiser/rdmo-catalog/tree/74e73503527213d0fcd9ebd48d8ba43fb545421b/rdmorganiser/questions/rdmo.xml)
  - [x] list the questions to be added (new from UA Ruhr project team)
  - [x] suggest domain attribute to refer to or a new one and create it 
  - [x] provide question text [en/de]
    - [x] add unit to project_duration (<unit>month</unit>) text lang=en month text lang=de=Monat  
  - [x] help text [en/de] 
  - [ ] ~~need conditions, or optionsets?~~

**Describe alternatives you've considered**

**Additional context**
Follow up ticket to #3

**Comment by Bassbiest** [comment]
~~This issue will be tackled once issue #9 and #11 are done since we currently have no method to keep track of the proposed changes.~~

**Comment by Bassbiest** [comment]
New Questions have now all necessary initial values and texts. For further improvements, we will use individual issues for each Question.
