### ISSUE TITLE
Provide RDM life cycle catalog list on GitHub pages

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#6]
**Is your feature request related to a problem? Please describe.**
The project group uses confluence wiki which is closed to the public. However, here we want to provide this first result, too. 

**Describe the solution you'd like**
Copy the html from confluence to the wiki of this repository.

**Describe alternatives you've considered**

**Additional context**

**Comment by jmfrenzel** [comment]
update on #5

**Comment by Bassbiest** [comment]
We decided to only provide the full UA Ruhr catalog at GitHub-pages, which is already the case at this point, so we will close this issue.
