### ISSUE TITLE
New question on data publication

### ISSUE THREAD

**Issue by smohex** [FDM-UARuhr/rdmo-catalog-uaruhr#60]
**Describe the request**  
Question about the place of publication and the existing interfaces is missing the storage colleagues

**Propose what exactly should be changed**  
There is a question about storing and archiving (ua_ruhr_v1.1.0-beta.1/storage-and-long-term-preservation/long-term-preservation-datasets/repository ), but not about publishing. Therefore I suggest a new question about it

**Proposed setting or content**   

*question text en*  
"Where should the data be published?"
*help text en*  
Please also provide information about existing interfaces that are offered to access the stored or archived data or information about what needs to be done to publish the data (on the infrastructure side).

*question text ger* 
"Wo sollen die Daten veröffentlicht werden?"
*help text ger*  
Bitte geben Sie auch Informationen zu existierenden Schnittstellen die angeboten werden um auf die gespeicherten oder archivierten Daten zuzugreifen bzw. Informationen darüber was gemacht werden muss damit die Daten (seitens der Infrastrukturen) veröffentlicht werden können.
**Additional context**
geforderte Schnittstellen wären auch interessant, wie CIFS, NFS, S3 etc., sowohl bei den Messgeräten als auch bei einer gewünschten anderweitigen Übertragung der Daten.

**From the following list delete everything that is NOT part of the content of your proposal. Once a subject of change is approved it will be marked accordingly in the list.**  

- [x] key repository
- [x] question text (en and ger)
- [x] help text (en and ger)
- [x] attribute /project/dataset/sharing/repository
- [x] question data-usage/data-sharing-and-re-use-publication/repository

**Comment by ClaraRosalie** [comment]
If question follows question "Will this dataset be published or shared?" (/data-usage/data-sharing-and-re-use-publication/yesno) add "If yes"/"Wenn ja" to proposed question text

**Comment by jmfrenzel** [comment]
relevance: rdmo, UA Ruhr, Proposal  catalogs 
PR  via rdmo-catalog

**question text en**
"Where should the data be published?"
**help text en**
Please provide information about the database/repository. 

question text ger
"Wo sollen die Daten veröffentlicht werden?"
help text ger
Nennen Sie die/das Datenbank/Repositorium, ggf. mit Link.

vote:
* RUB :+1: 
* UDE :+1: 
* TUDo :+1:

**Comment by jmfrenzel** [comment]
siehe https://github.com/rdmorganiser/rdmo-catalog/issues/55

**Comment by smohex** [comment]
Attribute created, the question was insertet behind "Sollte die Nachnutzung dieses Datensatzes Einschränkungen unterliegen, erläutern Sie bitte die Gründe." and before "Wenn ja, unter welchen Nutzungsbedingungen oder welcher Lizenz sollen die Daten veröffentlicht bzw. geteilt werden?"

**Comment by jmfrenzel** [comment]
implemented upstream https://github.com/rdmorganiser/rdmo-catalog/pull/59
