### ISSUE TITLE
remove entry in tools/cat_member.yml 

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#71]
**Describe the bug**
the path variable  `ua_ruhr/metadata-and-referencing/metadata/abstract` is not used 
it can be removed from
* in `tools/cat_member.yaml`

**Background**   
The content of the above  question is covered by `ua_ruhr/metadata-and-referencing/metadata-dataset/abstract`

see #69

**Comment by ClaraRosalie** [comment]
`ua_ruhr/metadata-and-referencing/metadata-dataset/abstract` is a valid path variable and could replace the one above

**Comment by jmfrenzel** [comment]
> `ua_ruhr/metadata-and-referencing/metadata-dataset/abstract` is a valid path variable and could replace the one above


The content of the above question is covered by `ua_ruhr/metadata-and-referencing/metadata-dataset/abstract`
