### ISSUE TITLE
Attributes used twice in UA Ruhr catalog

### ISSUE THREAD

**Issue by ClaraRosalie** [FDM-UARuhr/rdmo-catalog-uaruhr#74]
I found two attributes which appear twice in https://rdmo-demo.rd.ruhr-uni-bochum.de/questions/catalogs/7/:

1. The attribute `https://rdmorganiser.github.io/terms/domain/project/legal_aspects/official_approval/data_access_committee` is used for two different questions: 
     - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/data-usage/data-sharing-and-re-use-publication/restricted_access` / If there are restrictions on making the data openly accessible, how will restricted access be provided?
     - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/legal-and-ethics/sensitive-data-official_approval/data_access_committee` / Is a data access committee needed to handle access requests to the published data of the project?

2. The attribute `https://rdmorganiser.github.io/terms/domain/project/coordination/name` appears twice each with the same question but different question path variable:
    - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/general/topic-research_field/name` / Which persons or institutions are responsible for the project coordination?
    - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/general/project-partners-name/name` / Which persons or institutions are responsible for the project coordination?

**Comment by jmfrenzel** [comment]
I cannot reproduce 1. on that server and also not in the files [rdmorganiser/questions/ua_ruhr.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/rdmorganiser/questions/ua_ruhr.xml) and [tools/all_questions.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/tools/all_questions.xml)

1. The attribute `https://rdmorganiser.github.io/terms/domain/project/legal_aspects/official_approval/data_access_committee` is used for one~~two different~~ questions: 
     - ~~`https://rdmorganiser.github.io/terms/questions/ua_ruhr/data-usage/data-sharing-and-re-use-publication/restricted_access` / If there are restrictions on making the data openly accessible, how will restricted access be provided?~~
     - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/legal-and-ethics/sensitive-data-official_approval/data_access_committee` / Is a data access committee needed to handle access requests to the published data of the project?

**Comment by jmfrenzel** [comment]
I can reproduce in the files [rdmorganiser/questions/ua_ruhr.xml ](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/rdmorganiser/questions/ua_ruhr.xml) and [tools/all_questions.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/tools/all_questions.xml) , that 


2. The attribute `https://rdmorganiser.github.io/terms/domain/project/coordination/name` appears twice each with the same question but different question path variable:
    - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/general/topic-research_field/name` / Which persons or institutions are responsible for the project coordination?
    - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/general/project-partners-name/name` / Which persons or institutions are responsible for the project coordination?

The latter 
>  - `https://rdmorganiser.github.io/terms/questions/ua_ruhr/general/project-partners-name/name` / Which persons or institutions are responsible for the project coordination?

should be the correct (and only) question referencing that attribute see the file [rdmorganiser/questions/ua_ruhr.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/rdmorganiser/questions/ua_ruhr.xml) and [tools/all_questions.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/tools/all_questions.xml) which is in sync with upstream.

**Comment by ClaraRosalie** [comment]
I can still reproduce 1. on [rdmo-demo](https://rdmo-demo.rd.ruhr-uni-bochum.de/questions/catalogs/7/) - the same attribute is used for two different question path variables and questions.

**Comment by jmfrenzel** [comment]
https://github.com/rdmorganiser/rdmo-catalog/pull/20
