### ISSUE TITLE
Add catalog help texts  

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#76]
**Is your feature request related to a problem? Please describe.**
As a user I want to get a brief information  about the purpose of the catalog when I have to choose one catalog for a new project  

**Describe the solution you'd like**
Add catalog help texts in auto_catalog generation.  
* Use content of  
   * en https://www.ruhr-uni-bochum.de/researchdata/rdmo_new_project.html
   * de https://www.ruhr-uni-bochum.de/researchdata/de/rdmo_new_project.html
* [x] Partial implementation via xml `comment` entry https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/pull/79 ; however this is not visible in rdmo due to missing import/export feature see https://github.com/rdmorganiser/rdmo/issues/359
* [x] implementation via two new xml entries under `<catalog> `
   * `<help lang="en">Lorem ipsum ..</help>`   
   * `<help lang="de">Lorem ipsum ..</help>`
* can be used in rdmo once https://github.com/rdmorganiser/rdmo/issues/359 is implemented in rdmo and included in a future rdmo release 
* 

**Additional context**
Feature request to implement help texts in rdmo import export https://github.com/rdmorganiser/rdmo/issues/359

**Comment by smohex** [comment]
Catalogs (English version)
Catalog | Description 
-------  | ---------
UA Ruhr-Consultation | Do you need advice on creating a data management plan or on your RDM in general? Fill out this catalog and contact **your local RDM-Team** ([RUB ](https://www.ruhr-uni-bochum.de/researchdata/de/contact.html)/ [TUDO ](https://forschungsfoerderung.tu-dortmund.de/forschungsdatenmanagement/beratungsangebot/)/ [UDE](https://www.uni-due.de/rds/kontakt_formular.php)).
UA Ruhr-Application | Funding agencies are demanding more and more information on the handling of research data. Use this catalog if you want to document your data management for a grant application.
UA Ruhr-Archiving | Use this catalog if you plan to store the data in a central repository or archive. In addition to questions about data storage the catalog also contains some general project questions which are relevant, for example, to common meta data standards.
UA Ruhr-Training | This catalog complements the Moodle course “Research Data Management” ([RUB-Course](https://moodle.ruhr-uni-bochum.de/m/course/view.php?id=19338) / [UDE-Course](https://moodle.uni-due.de/course/view.php?id=20309) (PW: forschung)). It contains basic questions about organizing, documenting, archiving and publishing research data.
UA Ruhr | This catalog contains all questions and covers all relevant aspects of research data management including some domain-specific questions and is therefore rather extensive. Use this catalog if you want to organize the data management of a collaborative project or facility.
Horizon2020 | This catalog is specifically adapted to EU funding applications under Horizon2020.

Kataloge (Deutsche Version)
Katalog | Beschreibung
-------- | -----------
UA Ruhr-Beratung | Sie benötigen eine Beratung zur Erstellung eines Datenmanagenentplans oder allgemein zu Ihrem FDM? Füllen Sie diesen Katalog aus, und kontaktieren Sie **ihr lokales FDM-Team** ([RUB ](https://www.ruhr-uni-bochum.de/researchdata/de/contact.html)/ [TUDO ](https://forschungsfoerderung.tu-dortmund.de/forschungsdatenmanagement/beratungsangebot/)/ [UDE](https://www.uni-due.de/rds/kontakt_formular.php)).
UA Ruhr-Antrag | Fördergeber fordern im Antrag immer mehr Informationen zum Umgang mit Ihren Forschungsdaten. Nutzen Sie diesen Katalog, wenn Sie Ihr Datenmanagement für einen Antrag dokumentieren wollen.
UA Ruhr-Archiv | Nutzen Sie diesen Katalog, wenn Sie planen die Daten in einem zentralen Speicher, Archiv oder Repositorium abzulegen. Neben Fragen zur Datenspeicherung werden auch einige allgemeine Projektinformationen abgefragt, die zum Beispiel für gängige Metadatenstandards relevant sind.
UA Ruhr-Schulung | Dieser Katalog kann ergänzend zum Moodle-Kurs “Forschungsdaten managen” ([RUB-Kurs](https://moodle.uni-due.de/course/view.php?id=20309) / [UDE-Kurs](https://moodle.uni-due.de/course/view.php?id=20309) (PW: forschung)) ausgefüllt werden. Er umfasst grundlegende Fragen zur Organisation, Dokumentation, Archivierung und Publikation von Forschungsdaten.
UA Ruhr | In diesem Katalog sind alle Fragen enthalten. Er behandelt umfassend die verschiedenen Aspekte des Forschungsdatenmanagements, deckt Anforderungen verschiedener Disziplinen ab, und ist daher recht umfangreich. Nutzen Sie diesen Katalog, wenn Sie die Datenhaltung im Team oder Verbund organisieren möchten.
Horizon2020 | Dieser Katalog ist speziell angepasst auf EU-Förderanträge im Rahmen von Horizon2020.
