### ISSUE TITLE
Update questions on personal data wrt. GDPR

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#8]
**Is your feature request related to a problem? Please describe.**
The common questions provided by rdmo catalog need updates because of the EU GDPR, new German federal data protection act, and new NRW state  data protection act. 

**Describe the solution you'd like**
* [x] Add text changes to the wiki of this repository 
* [x] create PR at https://github.com/rdmorganiser/rdmo-catalog Note: change local description e.g. UA Ruhr specific terms into general terms 
*   [x] proir to the PR, make sure there is nothing specific to UARuhr left in the questions/help texts
* [x] update the UA ruhr catalog from #4 

**Describe alternatives you've considered**

**Additional context**

**Comment by Bassbiest** [comment]
The pull request #2 was merged into master. Closing Issue.
