### ISSUE TITLE
Update question content with latest upstream 

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#85]
**Is your feature request related to a problem? Please describe.**
./tools/all_questions.xml is not up do date with rdmorganiser/questions/rdmo.xml

A comparison shows 48 differences, i.e. new/removed questions; changed text; changed help text see https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/issues/85#issuecomment-906362632

**Describe the solution you'd like**
Update the content of ./tools/all_questions.xml with that of [rdmorganiser/questions/rdmo.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/6ceaeff0ddb1e76c80e95598bb2a8be05fe35ecc/rdmorganiser/questions/rdmo.xml) , but only for those changes that make sense for UA Ruhr question catalogs
* 1. Use comparison of removed "questions; changed text; changed help text"  as provided in the comment below https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/issues/85#issuecomment-906362632
* 2. keep UA Ruhr- specific content as beeing listed here https://fdm-uaruhr.github.io/rdmo-catalog-uaruhr/questions/ua_changes.html
* 3. add 'it' and 'fr' locale (needs translation of uaruhr specific questions)

**Additional context**
* this issue might resolve #74

**Comment by jmfrenzel** [comment]
URIs of the questions that have been (removed or updated text/help  at revision 9c8b89de4c075ee45550366da4c54bada8bedf33) when comparing upstream   [rdmorganiser/questions/rdmo.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/rdmorganiser/questions/rdmo.xml) and UA Ruhr  [tools/all_questions.xml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/9c8b89de4c075ee45550366da4c54bada8bedf33/tools/all_questions.xml)


/ua_ruhr/general/topic-research_question/title
old uri: /ua_ruhr/general/topic-research_field/name
/ua_ruhr/general/project-partners-partner/name
/ua_ruhr/general/project-partners-partner/rdm_policy
/ua_ruhr/general/project-partners-partner/contact
/ua_ruhr/general/funding-funder/funder_policy
/ua_ruhr/general/other-requirements-yesno/yesno
/ua_ruhr/general/other-requirements-requirements/requirements
/ua_ruhr/content-classification/data-dataset/description
/ua_ruhr/content-classification/data-reuse/scenario
/ua_ruhr/content-classification/data-reproducibility/reproducibility
/ua_ruhr/technical-classification/data-dates/data_collection_start
/ua_ruhr/technical-classification/data-dates/data_collection_end
/ua_ruhr/technical-classification/data-volume/volume
/ua_ruhr/technical-classification/data-volume/rate
/ua_ruhr/technical-classification/data-formats/format
/ua_ruhr/technical-classification/data-tools/creation_methods
/ua_ruhr/technical-classification/data-tools/usage_technology
/ua_ruhr/technical-classification/data-versioning/strategy
/ua_ruhr/data-usage/data-storage-and-security-storage/naming_policy
/ua_ruhr/data-usage/data-storage-and-security-data_security/access_permissions
/ua_ruhr/data-usage/data-storage-and-security-data_security/security_measures
/ua_ruhr/data-usage/data-sharing-and-re-use-publication/conditions
/ua_ruhr/data-usage/quality-assurance-dataset/measures
/ua_ruhr/data-usage/quality-assurance-integration/integration
/ua_ruhr/data-usage/costs-dataset/creation_personnel
/ua_ruhr/data-usage/costs-dataset/usage_personnel
/ua_ruhr/data-usage/costs-dataset/storage_personnel
/ua_ruhr/metadata-and-referencing/metadata-dataset/creation_semi_automatic
/ua_ruhr/metadata-and-referencing/metadata-costs/personnel
/ua_ruhr/metadata-and-referencing/structure-granularity-and-referencing-pids/subentities (specific content of UA Ruhr)
/ua_ruhr/metadata-and-referencing/structure-granularity-and-referencing-pids/name
/ua_ruhr/metadata-and-referencing/structure-granularity-and-referencing-costs/personnel
/ua_ruhr/metadata-and-referencing/structure-granularity-and-referencing-costs/non_personnel
/ua_ruhr/legal-and-ethics/sensitive-data-personal_data_yesno/yesno
/ua_ruhr/legal-and-ethics/sensitive-data-privacy_law/privacy_law
/ua_ruhr/legal-and-ethics/sensitive-data-personal_data/bdsg_3_9
/ua_ruhr/legal-and-ethics/sensitive-data-personal_data/extent
/ua_ruhr/legal-and-ethics/sensitive-data-costs/anonymization_personnel
/ua_ruhr/legal-and-ethics/sensitive-data-costs/anonymization_non_personnel
/ua_ruhr/legal-and-ethics/sensitive-data-costs/security_personnel
/ua_ruhr/legal-and-ethics/sensitive-data-costs/security_non_personnel
/ua_ruhr/legal-and-ethics/intellectual-property-rights-yesno/yesno
/ua_ruhr/legal-and-ethics/intellectual-property-rights-costs/personnel
/ua_ruhr/storage-and-long-term-preservation/selection-criteria/selection_criteria
/ua_ruhr/storage-and-long-term-preservation/long-term-preservation-datasets/yesno
/ua_ruhr/storage-and-long-term-preservation/long-term-preservation-datasets/purpose
/ua_ruhr/storage-and-long-term-preservation/long-term-preservation-datasets/certification

**Comment by ClaraRosalie** [comment]
For 
- /ua_ruhr/content-classification/data-dataset/description
- /ua_ruhr/technical-classification/data-dates/data_collection_start 
- /ua_ruhr/technical-classification/data-dates/data_collection_end

old question content was kept because it has been intentionally changed by UA Ruhr.
