### ISSUE TITLE
Indentify changes rdmo.xml questions (2018) and UA Ruhr draft, update the draft 

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#9]
**Is your feature request related to a problem? Please describe.**
Once #3 and #7 have been PR to https://github.com/rdmorganiser/rdmo-catalog we use this as a basis for updating the UA Ruhr draft (still being based on [v0.1.0](https://github.com/rdmorganiser/rdmo-catalog/tree/v0.1.0)

**Describe the solution you'd like**
* [x] generate new html table with attribute uri's, question texts, (helptext) based on the result of #3 and #7
* [x] migrate the new and updated questions from the draft html ( uri's, question texts, (helptext)
   * [x] publish on gh-pages branch
* [x] discussion (confluence) 
* [x] generate rdmo.xml 
   * [x] replace `rdmorganiser.github.io` by `rdmorganiser.uaruhr.de`

**Describe alternatives you've considered**

**Additional context**

**Comment by Bassbiest** [comment]
I suggest using the productive UA Ruhr instance of RDMO as URI-prefix instead of rdmorganiser.uaruhr.de

**Comment by jmfrenzel** [comment]
Makes sense

**Comment by Bassbiest** [comment]
I don't know whether or not the prefix can be changed without causing trouble in RDMO. If that is not a problem, then this is quite easily done using search and replace functionality.

**Comment by jmfrenzel** [comment]
URI-prefix alignment with productive UA Ruhr instance moved to a new issue
